fun main() {
    val person = Person("Jek",38)
    person.show()
    person.learn()
    person.walk()
    person.eat()
    println("-----------------")
    val dancer = Dancer("Rich",40,"Bar")
    dancer.groupName
    dancer.groupNameDancer()
    dancer.show()
    dancer.learn()
    dancer.walk()
    dancer.eat()
    dancer.designationDancer()

    println("-----------------")
    val singer = Singer("Makl",39,"Club")
    singer.groupNameSinger()
    singer.show()
    singer.learn()
    singer.walk()
    singer.eat()
    singer.designationSinger()
    println("-----------------")
    val programmer = Programmer("Ali",25,"Com company")
    programmer.groupNameProgrammer()
    programmer.show()
    programmer.learn()
    programmer.walk()
    programmer.eat()
    programmer.designationProgrammer()
    println("-----------------")
}